spring:
  application:
    name: iubBakend
  datasource:
    url: jdbc:mysql://localhost:3306/iubdata
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

  mail:
    host: mail.iub-university.com
    port: 587
    username: ${EMAIL_USERNAME:secretariat@iub-university.com}
    password: ${EMAIL_PASSWORD:Secretariat@2025}  # Corrigé
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          ssl:
            trust: mail.iub-university.com
        debug: true
server:
  port: 8080

# Configuration CORS
cors:
  allowed-origins: http://localhost:4200,http://localhost:3000

# Configuration des uploads
app:
  upload:
    actualites:
      dir: uploads/actualites
    directeurs:
      dir: uploads/directeurs

  email:
    from: ${EMAIL_FROM:secretariat@iub-university.com}
    secretariat: secretariat@iub-university.com


# Configuration Swagger/OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true